[package]
name = "dbot"
version = "0.0.0"
edition = "2021"

[dependencies]
globset = "0.4"
serde_yaml = "0.9"
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.serde]
version = "1.0"
features = ["derive"]
